<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sales Report PDF</title>
    <style>
        .sales-container {
    max-width: 900px;
    margin: auto;
    padding: 25px;
    background: #fdfdfd;
    border: 1px solid #ccc;
    border-radius: 10px;
    box-shadow: 0 0 8px rgba(0,0,0,0.05);
}
.report-header {
    text-align: center;
    margin-bottom: 30px;
}
.logo-img {
    width: 90px;
    height: 90px;
    border-radius: 50%;
    object-fit: cover;
    border: 2px solid #ccc;
    margin-bottom: 15px;
}
.report-title {
    font-size: 28px;
    font-weight: bold;
    margin: 0;
    color: #333;
}
.date-range {
    font-size: 16px;
    color: #555;
    margin-top: 8px;
}
.summary-text {
    font-size: 15px;
    color: #444;
    margin-bottom: 25px;
    text-align: justify;
}
.client-record-table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 30px;
}
.client-record-table th,
.client-record-table td {
    border: 1px solid #ddd;
    padding: 12px 15px;
    text-align: left;
}
.client-record-table th {
    background-color: lightblue;
    color: black;
}
.client-record-table tr:nth-child(even) {
    background-color: #f2f2f2;
}
.client-record-table tr:hover {
    background-color: #f2f2f2;
}
.total-summary-row {
    font-weight: bold;
    background-color: #f2f2f2;
    color: black;
}
.meta-info {
    font-size: 14px;
    color: #777;
    text-align: right;
    margin-top: 25px;
}
.signature-section {
    margin-top: 50px;
    text-align: left;
    font-size: 14px;
    color: #333;
}
.pdf-button-container {
    text-align: right;
    margin-top: 25px;
}
.btn-save-pdf {
    background-color: #00897b;
    color: white;
    padding: 10px 18px;
    border-radius: 6px;
    text-decoration: none;
    font-size: 16px;
}
.btn-save-pdf:hover {
    background-color: #45a049;
}
.report-footer {
    text-align: center;
    font-size: 13px;
    color: #666;
    margin-top: 40px;
    border-top: 1px solid #ccc;
    padding-top: 10px;
}
</style>
</head>
<body>
<div class="sales-container">
    <!-- Report Header -->
    <div class="report-header text-center">
        <img src="{{ public_path('pictures/images1.jpg') }}" alt="Bekam Asy Syifa Logo" class="logo-img">
        <h2 class="report-title">SALES REPORT</h2>
        <p class="date-range">Date Range: {{ $fromDate }} to {{ $toDate }}</p>
    </div>

   
    <!-- Table -->
    <table class="client-record-table">
        <thead>
            <tr>
                <th>Package Name</th>
                <th>Times Taken</th>
                <th>Subtotal (RM)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($results['packages'] as $row)
                <tr>
                    <td>{{ $row['name'] }}</td>
                    <td>{{ $row['count'] }}</td>
                    <td>{{ number_format($row['subtotal'], 2) }}</td>
                </tr>
            @endforeach
            <tr class="total-summary-row">
                <td>Total</td>
                <td>{{ $results['total_appointments'] }}</td>
                <td>RM {{ number_format($results['total_sales'], 2) }}</td>
            </tr>
        </tbody>
    </table>

    <!-- Metadata -->
    <p class="meta-info">
        Generated by: {{ Auth::user()->name }}<br>
        Generated on: {{ \Carbon\Carbon::now()->format('d M Y, h:i A') }}
    </p>

    <!-- Signature -->
    <div class="signature-section">
        <p>___________________________</p>
        <p>Authorized Signature</p>
    </div>

    <!-- PDF Button -->
    <div class="pdf-button-container">
        <a href="{{ route('sales.report.pdf', ['from_date' => $fromDate, 'to_date' => $toDate]) }}" class="btn-save-pdf">
            <i class="fa fa-save"></i> Save as PDF
        </a>
    </div>

    <!-- Footer -->
    <div class="report-footer">
        <p>Bekam Asy Syifa | No. 123, Jalan Sejahtera, Selangor</p>
        <p>Email: contact@bekamasysyifa.com | Phone: 03-1234 5678</p>
    </div>
</div>
</body>
</html>
